package com.web.dto;

// default package
// Generated Feb 8, 2015 10:30:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Demo generated by hbm2java
 */
public class Demo implements java.io.Serializable {

	private String id;
	private String name;
	private Date dob;
	private Integer salary;

	public Demo() {
	}

	public Demo(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public Demo(String id, String name, Date dob, Integer salary) {
		this.id = id;
		this.name = name;
		this.dob = dob;
		this.salary = salary;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public Integer getSalary() {
		return this.salary;
	}

	public void setSalary(Integer salary) {
		this.salary = salary;
	}

}
